unset KUN_PRIMARY HERDR_ENV HERDR_CONFIG_PATH HERDR_SESSION FM_ROOT_OVERRIDE FM_CONFIG_OVERRIDE FM_STATE_OVERRIDE FM_GATE_REFUSE_BYPASS
export HOME="$PWD/.v/h"
export XDG_CONFIG_HOME=.v/c
export XDG_RUNTIME_DIR="$PWD/.v/r"
export TMPDIR="$PWD/.v/t"
export FM_HERDR_LAB_PROTECTED_SESSION=proof5
export FM_HERDR_LAB_STATE_DIR="$PWD/.v/tripwires"
export FM_HOME="$PWD/.v/fleet"
export SHELL=/bin/bash
